version: "4.12.0"

services:
  database:
    container_name: vial-backend-b
    image: postgres:latest
    environment:
      POSTGRES_USER: vial
      POSTGRES_PASSWORD: vial
      POSTGRES_DB: vial
    ports:
      - 5432:5432
  nodeserver:
    container_name: vial-backend-b-api
    image: node:18.15.0
    build:
      context: .
      dockerfile: Dockerfile.local
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - 8080:8080
  frontend:
    container_name: vial-frontend
    image: node:18.15.0
    working_dir: /usr/app/frontend
    volumes:
      - ./frontend:/usr/app/frontend
      - /usr/app/frontend/node_modules
    command: npm run dev
    ports:
      - 5173:5173
    depends_on:
      - nodeserver